### ISSUE TITLE
Create project without creating github repo

### ISSUE THREAD

**Issue by andreabettich** [faessler/strapi-gcp-installer#2]
Add an option, to create the project but without creating an Github repo.

Reason: Don't need the cli and can live without it ;)

```
/bin/sh: gh: command not found

⛔️ ERROR:
Command "gh" is not installed!

Run the following command to fix this error:
$ brew install gh

Docs: https://github.com/cli/cli#installation
```

**Comment by andreabettich** [comment]
There is an option to skip it but it seems to be there for another reason?

https://github.com/faessler/strapi-gcp-installer/blob/main/src/actions/createGitHubRepository.ts#L10

**Comment by faessler** [comment]
Good idea, will implement it :-)

**Comment by faessler** [comment]
`npx strapi-gcp-installer <folder> --github-actions=false`
